export const TRANSACTIONS_REPOSITORY = Symbol("TRANSACTIONS_REPOSITORY");
export const DELIVERY_REPOSITORY = Symbol("DELIVERY_REPOSITORY");
export const CREATE_TRANSACTION = Symbol("CREATE_TRANSACTION");
export const WEBHOOK_HANDLER = Symbol("WEBHOOK_HANDLER");
