export const TRANSACTIONS_REPOSITORY = Symbol("TRANSACTIONS_REPOSITORY");
export const DELIVERY_REPOSITORY = Symbol("DELIVERY_REPOSITORY");
export const CUSTOMER_REPOSITORY = Symbol("CUSTOMER_REPOSITORY");
export const CREATE_TRANSACTION = Symbol("CREATE_TRANSACTION");
